### ISSUE TITLE
Problem compiling dsniff

### ISSUE THREAD

**Issue by SKT-T1-Faker2004** [ggreer/dsniff#13]
When I move on to the step "make" it turned out that:

./ssh.c:398:26: error: incomplete definition of type 'struct rsa_st'
        get_bn(ssh->ctx->hostkey->e, &p, &i);
               ~~~~~~~~~~~~~~~~~^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:110:16: note: forward
      declaration of 'struct rsa_st'
typedef struct rsa_st RSA;

And this error happens many times

What's wrong?

plz, reply soon.

**Comment by atomiechen** [comment]
I've got the same errors. Look around and guess it's a problem of openssl 1.1 installed by Homebrew for the newer version alters API. 

Maybe downgrading openssl to 1.0 can solve this, but i have not tried and it seems not so convenient because this version of openssl is no longer available via Homebrew, and you need to build yourself. A ref page about install openssl 1.0.2: https://stackoverflow.com/questions/59337838/openssl-1-0-2m-on-macos

A better solution is to update dsniff itself. Wait for it...
